### ISSUE TITLE
CSS asset URLs are incorrect when --entry-names is used

### ISSUE THREAD

**Issue by kaksmet** [evanw/esbuild#1044]
Running
```
esbuild index.css --bundle --outdir=build --entry-names=styles/[name] --asset-names=assets/[name] --loader:.png=file
```
with `index.css` looking like
```css
.foobar {
    background-image: url(./foobar.png);
}
```
results in `build/styles/index.css`:
```css
/* index.css */
.foobar {
  background-image: url(./assets/foobar.png);
}
```
Since `foobar.png` is copied to `build/assets/foobar.png` the URL should actually be `../assets/foobar.png`?
