### ISSUE TITLE
CSS minificator incorrectly removes property with `!important` value.

### ISSUE THREAD

**Issue by SevInf** [evanw/esbuild#1372]
When CSS rule declares the same property twice, earlier declaration with `!important` modifier and later one without it, CSS minified incorrectly keeps the later one.

Steps to reproduce:

1. Create `style.css` with following content:

```css
.selector {
  padding: 10px !important;
  padding: 0;
}
```

2. Run `esbuild --minify style.css`

Expected output:

```css
.selector{padding:10px!important}
```

Actual output:
```css
.selector{padding:0}
```

I acknowledge that original thing is a pretty silly code to write and should probably be caught by a linter. Nevertheless, this introduces a difference between minified and non-minified code.

**Comment by mixtur** [comment]
@evanw Why keep both `padding:0` and `padding:10px!important`? AFAICT `padding:0` is safe to be removed there. (From the example in the changelog.md)

**Comment by evanw** [comment]
Because it’s a rare edge case that doesn’t matter for minification sizes in practice. The result shouldn’t be incorrect, however.

**Comment by mixtur** [comment]
This pattern is easy to overlook when using preprocessors. e.g.

```scss
// mixin-library.scss
@mixin abc() {
  padding: 10px !important;
}

//actual-styles.scss
@import "mixin-library.scss"
.selector {
  +abc();
  padding: 0;
}
```

But yes this is probably rare.
