### ISSUE TITLE
[CSS] variables missing space after colon

### ISSUE THREAD

**Issue by hyrious** [evanw/esbuild#1571]
Input:
```css
body {
--variable:red;
color:red
}
```
Output:
```css
body {
  --variable:red; /* <- expect ': ' */
  color: red;
}
```
[see it live](https://hyrious.me/esbuild-repl/?version=0.12.25&shareable=JTdCJTIyY29kZSUyMiUzQSUyMmJvZHklMjAlN0IlNUNuLS12YXJpYWJsZSUzQXJlZCUzQiU1Q25jb2xvciUzQXZhcigtLXZhcmlhYmxlKSU1Q24lN0QlMjIlMkMlMjJjb25maWclMjIlM0ElN0IlMjJsb2FkZXIlMjIlM0ElMjJjc3MlMjIlN0QlN0Q%3D)
