### ISSUE TITLE
Compile time calc() in CSS

### ISSUE THREAD

**Issue by xPaw** [evanw/esbuild#1607]
Example:
```css
.test {
	max-width: calc(280px * 2 + 20px);
}

@media (max-width: 580px) {
	.test {
		max-width: calc(280px + 20px);
	}
}
```

Since these calculations have const values, it would be possible to just calculate it and output:
```css
.test {
	max-width: 580px;
}

@media (max-width: 580px) {
	.test {
		max-width: 300px;
	}
}
```

Is this something esbuild could/should do as part of the minification?
