### ISSUE TITLE
`rgba()` value after minify will get a `0.002` increase in its alpha value

### ISSUE THREAD

**Issue by sodatea** [evanw/esbuild#1682]
#### Reproduction

```sh
echo "div { color: rgba(100, 100, 100, 0.5); }\n" | esbuild --minify --loader=css --target=chrome61
```

#### Output

```css
div{color:rgba(100,100,100,.502)}
```

#### Expected output

```css
div{color:rgba(100,100,100,.5)}
```
