### ISSUE TITLE
Produces invalid css when using inherit for part of border-radius

### ISSUE THREAD

**Issue by wotnak** [evanw/esbuild#1702]
```css
div {
  border-radius: inherit;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
```
should be left as is but is transformed to 
```css
div {
  border-radius: inherit 0 0 inherit;
}
```
`inherit` can only be used as the whole value of a given property. Using it as part of a shorthand property value results in browsers regarding the entire value as invalid. Similar behavior is used for other explicit defaulting keywords (`unset`, `initial`) https://www.w3.org/TR/css-cascade-3/#defaulting-keywords.

Basically https://github.com/evanw/esbuild/issues/1657 but for border-radius.
