### ISSUE TITLE
Improve minify css result.

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#1755]
### Description

The minified css result is not expected.

### Input 
``` css
.a {
    color: red;
}

.b {
    color: red;
}

.a {
    color: red;
}
````

### Output
```css
.b{color:red}.a{color:red}
```

### Expected 

``` css
.b,.a{color:red}
```
