### ISSUE TITLE
CSS minification combines vendor-specific selectors creating invalid rules

### ISSUE THREAD

**Issue by adamwathan** [evanw/esbuild#1776]
If you feed something like this into esbuild's CSS minification:

```css
.form-input:-moz-placeholder-shown {
  color: black;
}
.form-input:-ms-input-placeholder {
  color: black;
}
.form-input:placeholder-shown {
  color: black;
}
```

...you get this output:

```css
.form-input:-moz-placeholder-shown,
.form-input:-ms-input-placeholder,
.form-input:placeholder-shown {
  color: black;
}
```

This unfortunately breaks the rule completely because Chrome has no idea what `-ms-input-placeholder` is for example and marks the entire rule as invalid and doesn't apply it.

In this example, the selectors should not be combined since they can't be combined safely and the output should remain as:

```css
.form-input:-moz-placeholder-shown {
  color: black;
}
.form-input:-ms-input-placeholder {
  color: black;
}
.form-input:placeholder-shown {
  color: black;
}
```

Twitter thread where this surfaced just in case helpful: https://twitter.com/mmmykolas/status/1460249898499166211

Thanks as always for your amazing work on this project! 🙌
