### ISSUE TITLE
Legal comments in CSS are removed when empty legal comments are present

### ISSUE THREAD

**Issue by adamwathan** [evanw/esbuild#1796]
Given this input:

```css
.example {
  --some-var: var(--tw-empty, /*!*/ /*!*/);
}

/*! I_need_this_comment */

body {
  background-color: red;
}
```

esbuild produces this output when running `esbuild ... --legal-comments=inline`:

```css
.example {
  --some-var: var(--tw-empty, );
}

body {
  background-color: red;
}
```

Removing the `/*!*/ /*!*/` nonsense is probably fine (we have to do it in Tailwind to preserve the whitespace between them in some overly aggressive minifiers), but I would at least expect the `/!* I_need_this_comment */` comment to be preserved.

If you remove the this line, the comment is preserved as expected:

```diff
  .example {
-   --some-var: var(--tw-empty, /*!*/ /*!*/);
  }
  
  /*! I_need_this_comment */
  
  body {
    background-color: red;
  }
```

Related: https://github.com/tailwindlabs/tailwindcss/issues/6182

Thanks!
