### ISSUE TITLE
[CSS minifier] The infinity keyword should be preserved in calc()

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#1839]
```css
.foo {
  width: calc(infinity * 2);
  height: calc(infinity * 1px);
  padding: calc(InFiNiTy);
}
```

esbuild 0.14.2 output: 

```css
.foo{width:Infinity;height:Infinitypx;padding:Infinity}
```
## Expectations
Maintain the output as is.

CSS Spec: https://drafts.csswg.org/css-values/#calc-error-constants

I'm not sure if `infinity/-infinity` will trigger this bug in other calculation functions.
Perhaps we should do a thorough check of similar issues to ensure that the new CSS syntax is not broken.
