### ISSUE TITLE
Questions about the order of css `@import`

### ISSUE THREAD

**Issue by bvanjoi** [evanw/esbuild#1946]
> version: 0.14.11

When I attempt to build following css files:

```css
/* entry.css */
@import url('./lib1.css');

.entry {
  color: blue;
}

@import url('./lib2.css');

/* lib1.css */
.lib1 {
  color: red;
}

/* lib2.css */
.lib2 {
  color: green;
}
```

The result of `esbuild entry.css --bundle`:

![image](https://user-images.githubusercontent.com/30187863/150171747-3886c0ff-22bb-4e57-af41-61dd88e046ae.png)

And the result of `esbuild entry.css`:

![image](https://user-images.githubusercontent.com/30187863/150171690-7b477a31-6000-4ab6-be58-67d06c3f5609.png)

Despite the warning alert, I still don't understanding why `lib2.css` had bundled, and even its order has changed.

According [css @import rules defined by w3c](https://drafts.csswg.org/css-cascade-4/#at-import), The results I expect to get is:

```css
.lib1 {
  color: red;
}

.entry {
  color: blue;
}
```

`postcss-import` will also give the above result.

So my question is: why just warn, but not eliminate `lib2.css` ? Maybe it's for performance reasons, or maybe the order doesn't matter?
