### ISSUE TITLE
Duplicate CSS rule declarations not being removed when there is a comment in between

### ISSUE THREAD

**Issue by alan-agius4** [evanw/esbuild#2016]
Duplicate CSS rules declarations are not being removed when there is a comment in between the duplicate rules.

Example in the below case `.mat-calendar` is defined with the same CSS rules twice. 

```css
.mat-calendar {
  font-family: Roboto, "Helvetica Neue", sans-serif;
}

/*!*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss ***!
  \*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/

.mat-calendar {
  font-family: Roboto, "Helvetica Neue", sans-serif;
}

.mat-select {
  font-family: Roboto, "Helvetica Neue", sans-serif;
}

```

```
$ esbuild styles.css --minify | grep 'mat-calendar' | wc -l
 2
```

Output (Prettied for convenience.)
```css
.mat-calendar {
  font-family: Roboto, Helvetica Neue, sans-serif;
} /*!*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss ***!
  \*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
.mat-calendar,
.mat-select {
  font-family: Roboto, Helvetica Neue, sans-serif;
}

```

Esbuild version 0.14.21
