### ISSUE TITLE
css-minifier: some compression rules fail when `@keyframes` are inside `@layer`

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2027]
```css
@layer foo {
  @keyframes     slide-left    {
    from   { width: 200px; }
    100%   { width: 500px; }
  }
}
```

esbuild output:

```
@layer foo{@keyframes slide-left {from {width: 200px;} 100% {width: 500px;}}}
```
## Expectation

No problem when there is no `@layer`. https://caniuse.com/mdn-css_at-rules_layer

```css
@layer foo{@keyframes slide-left{0%{width:200px}to{width:0}}}
```
