### ISSUE TITLE
[css-minifier] Support @font-feature-values

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2117]
https://caniuse.com/mdn-css_at-rules_font-feature-values
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values

```css
/* At-rule for "nice-style" in Font Two */
@font-feature-values Font Two {
  @styleset {
    nice-style: 4;
  }
}

/* Apply the at-rules with a single declaration */
.nice-look {
  font-variant-alternates: styleset(nice-style);
}
```
