### ISSUE TITLE
[css-minifier] do not escape invisible characters

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2124]
We usually do some special hacking with invisible characters, which will become unreadable after escaping and hard to read the CSS code when debugging.

For escaped characters, it is safest to convert only case and compress the length of Unicode characters. See also: https://mathiasbynens.be/notes/css-escapes

For example: 

- `\000A` => `\a`
- `\0020` => `\20`
-  `\9` => `\9`

## Input

The following example is from: https://lea.verou.me/2012/02/flexible-multiline-definition-lists-with-2-lines-of-css/

```css
:not(#\9) .foo {
  font-family: \000A;
}

dd:after {
  content: "\A" "\0009" "Hello" "\3A";
  white-space: pre;
}
```

## Output

```css
:not(#\	) .foo{font-family:\a}dd:after{content:"\a" "	" "Hello" "\:";white-space:pre}
```

## Expected

```
:not(#\9) .foo{font-family:\a}dd:after{content:"\a" "\9" "Hello" "\3a";white-space:pre}
```
