### ISSUE TITLE
esbuild creating whitespace around css variables, making them unusable in Chromium

### ISSUE THREAD

**Issue by Braweria** [evanw/esbuild#2132]
I am using esbuild to generate my JS and CSS files. I just started the project, and I can say that it will use a lot of CSS variables, here is an example:

```css
:root .monochrome-spectrum,
.theme-dark.monochrome-spectrum {
  --monochrome-hue: 50;
  --monochrome-saturation: 30;
  --monochrome-lightness: 30;
  /* prettier-ignore */
  --monochrome-hsl: hsl(
    var(--monochrome-hue)deg,
    var(--monochrome-saturation)%,
    var(--monochrome-lightness)%
  );
  --main-node: var(--monochrome-hsl);
}
```

Note how `--monochrome-hsl` is build. Variable and then the unit, no spaces. But when I bundle my file, a space was added, making it unusable.

![image](https://user-images.githubusercontent.com/62669899/160240807-04859cac-fcd9-42f4-85e5-57d6b7ce0817.png)

The Stylesheet is used in an Electron App (Obsidian).

**Comment by evanw** [comment]
I can't reproduce this. This is esbuild's output with bundling and without minification:

```css
:root .monochrome-spectrum,
.theme-dark.monochrome-spectrum {
  --monochrome-hue: 50;
  --monochrome-saturation: 30;
  --monochrome-lightness: 30;
  --monochrome-hsl: hsl( var(--monochrome-hue)deg, var(--monochrome-saturation)%, var(--monochrome-lightness)% );
  --main-node: var(--monochrome-hsl);
}
```

and with bundling and minification:

```css
:root .monochrome-spectrum,.theme-dark.monochrome-spectrum{--monochrome-hue: 50;--monochrome-saturation: 30;--monochrome-lightness: 30;--monochrome-hsl: hsl( var(--monochrome-hue)deg, var(--monochrome-saturation)%, var(--monochrome-lightness)% );--main-node: var(--monochrome-hsl)}
```

In both cases there is no space inserted in between `var()` and `deg`. Can you provide the esbuild configuration that reproduces this issue?

**Comment by evanw** [comment]
I noticed `/* prettier-ignore */` and I thought I'd try this in Prettier. It turns out Prettier messes up this syntax. This is a Prettier bug, not an esbuild bug. Here's Prettier's output on that code:

```css
:root .monochrome-spectrum,
.theme-dark.monochrome-spectrum {
  --monochrome-hue: 50;
  --monochrome-saturation: 30;
  --monochrome-lightness: 30;
  --monochrome-hsl: hsl(
    var(--monochrome-hue) deg,
    var(--monochrome-saturation) %,
    var(--monochrome-lightness) %
  );
  --main-node: var(--monochrome-hsl);
}
```

I think like this is the Prettier bug you're looking for: https://github.com/prettier/prettier/issues/5407. I'm closing this issue as nothing appears to be wrong with esbuild here.
