### ISSUE TITLE
How to to define the home directory (~/) in a css url

### ISSUE THREAD

**Issue by doberkofler** [evanw/esbuild#2213]
When using `url` in the `css loader` of `esbuild` I have been using the ` ~/` prefix to specify the home directory in `webpack`.
This is a very helpful url notation that allows to start at the root of the project instead of having relative (../) paths that change when files are moved around in the directory structure.
This is not supported or does not seem to work in `esbuild` and I was looking for a possible explanation or alternative on how to solve this important use case.

```css
.foo {
   background: transparent url("~/smiley.png") no-repeat scroll 0 0;
}
```
