### ISSUE TITLE
css transform does not end when css is lacking a closing bracket in selector

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2276]
When input css has an invalid syntax (lacking a closing bracket in selector), esbuild `transform` does not end.

For example:
```css
:where( {}
```
and
```css
:where(blockquote, :not(ltr) {
  border-left-width: 3px
}
:where(blockquote, :not(rtl) {
  border-right-width: 3px
}
```

Original issue: https://github.com/vitejs/vite/issues/8034
My thoughts: https://github.com/vitejs/vite/issues/8034#issuecomment-1119221149
Reproduction: [stack blitz](https://stackblitz.com/edit/node-rn8h4a?file=esbuild.js) (`node esbuild.js`)
