### ISSUE TITLE
pnp: `esbuild@0.15.2` unable to resolve range dependencies

### ISSUE THREAD

**Issue by bryanjtc** [evanw/esbuild#2464]
D3 packages use ranges in their dependencies. Example: https://github.com/d3/d3-scale/blob/main/package.json
When I use this d3-scale, yarn installs the dependencies and sets the latest version in that range as the resolution.
One of the dependencies of d3-scale is d3-time.
Yarn.lock:
```yml
"d3-time@npm:2.1.1 - 3":
  version: 3.0.0
  resolution: "d3-time@npm:3.0.0"
  dependencies:
    d3-array: 2 - 3
  checksum: 01646568ef01682550b7ee9f32394e4eb116a29515564861958871ed8de8fff02a25cd50dd8c4413921e6d9ecb8c8ce39be3266f655c8c18599fe58bcb253d60
  languageName: node
  linkType: hard
```
Esbuild can't resolve d3-time
![image](https://user-images.githubusercontent.com/49354825/184470274-e565e46d-5181-4316-86e5-331221cdbeb1.png)
