### ISSUE TITLE
esbuild doesn't recognize certain CSS url()

### ISSUE THREAD

**Issue by cnshenj** [evanw/esbuild#2482]
[esbuild doc](https://esbuild.github.io/content-types/#css) says it supports CSS url(): "You can @import other CSS files and reference image and font files with url() and esbuild will bundle everything together"

Here is an example: https://github.com/cnshenj/azdo-ext
I added a custom plugin to print out the files that are not loaded properly:
```js
  loader: {
    ".woff": "copy"
  },
  plugins: [
    {
      name: "Logger",
      setup(build) {
        build.onResolve({ filter: /(?:FabricIcons\.css|AzDevMDL2)/ }, async (args) => {
          console.log(args.path);
          return { path: path.resolve(args.resolveDir, args.path) };
        });
      }
    },
```
This file is being imported: `FabricIcons.css`. It contains these lines:
```css
@font-face {
  font-family: "AzureDevOpsMDL2Assets";
  src: url("./fonts/AzDevMDL2.woff") format("woff");
}
```

But `AzDevMDL2.woff` is not imported and the font file is not copied to `outdir`.

You can repro this issue by:
1. `npm i`
2. `node build.mjs`
