### ISSUE TITLE
[css-minifier]Merge the same rules

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2553]
Currently cssnano, lightningcss are all supported.

## Input
```css
a:not([href]) {
  color: inherit;
  text-decoration: none
}

a:not([href]):hover {
  color: inherit;
  text-decoration: none
}
```

## Output

```css
a:not([href]){color:inherit;text-decoration:none}a:not([href]):hover{color:inherit;text-decoration:none}
```

## Expected

```css
a:not([href]),a:not([href]):hover{color:inherit;text-decoration:none}
```
