### ISSUE TITLE
[css-minifier] Correctly parsed and compressed <keyframes-name> = <string> 

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2555]
## Spec

```
<keyframes-name> = <custom-ident> | <string>
```

https://drafts.csswg.org/css-animations/#typedef-keyframes-name

Often `<string>` can be compressed to `<custom-ident>`, However, **CSS-wide keywords** and `none` must remain in quotation marks.

## Input

```css
@keyframes "one two" {
  0% {
    left: 100px;
  }
}

@keyframes "none" {
  to {
    right: 100px;
  }
}

.foo {
  animation-name: "none", "unset", "one two";
}
```

## Actual  output

This WPT PR has more detailed test cases. https://github.com/web-platform-tests/wpt/pull/35903

```css
@keyframes ""{0%{left:100px}}@keyframes ""{to{right:100px}}.foo{animation-name:"none","unset","one two"}
```

## Expected

```css
@keyframes one\ two{0%{left:100px}}@keyframes"none"{to{right:100px}}.foo{animation-name:"none","unset",one\ two}
```
