### ISSUE TITLE
[css-minifier] colors in CSS custom properties are not compressed

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2566]
## Input

```css
:root {
    --primary-dark: lightblue;
    --white: white;
    --foo: #FFFFFF;
}
```

## Output

```css
:root{--primary-dark: lightblue;--white: white;--foo: #FFFFFF}
```

**Comment by evanw** [comment]
That's expected. CSS variables are arbitrary token sequences and don't have specific semantics. You can also read the value of a CSS variable from JavaScript so doing what you suggested could introduce bugs.

**Comment by yisibl** [comment]
We may have to analyze if the variables are referenced elsewhere, at which point they will be of the specified type.

E.g.

```css
:root {
    --primary-dark: lightblue;
    --white: white;
    --foo: #FFFFFF;
}

.bg {
  background: var(--foo);
}
```
