### ISSUE TITLE
CSS escaping breaks specific unicode-range values

### ISSUE THREAD

**Issue by matthi4s** [evanw/esbuild#2677]
When declaring a `@font-face` with one or multiple `unicode-range` values, very specific ranges get escaped which breaks the value and the entire `unicode-range` declaration.

`test.css`
```css
@font-face {
    unicode-range: U+0e2e-0e2f;
}
```

`build`
```bash
esbuild test.css --outfile=output.css
```

`output.css`
```css
@font-face {
  unicode-range: U+0e2\65-0e2f;
}
```
The `e` was escaped to `\65`, which is invalid CSS.
This was tested on esbuild 0.15.14.

Playing around with this, it seems like this is triggered by the sequence `[0-9]e[0-9]e-[0-9]`. I've also looked around the source code and my guess is that this is caused by this part: https://github.com/evanw/esbuild/blob/c9b24d829cfb8a08d4ade8d7d78bee568f163270/internal/css_printer/css_printer.go#L632-L640
