### ISSUE TITLE
CSS optimisations

### ISSUE THREAD

**Issue by Inqnuam** [evanw/esbuild#2936]
Hello @evanw 
Is is possible to deduplicate and move all @import and @font-face rules to the top of css bundle as you do with @charset?

**Comment by evanw** [comment]
Please provide an example of what you want the input and output to be. There isn't enough information here to know what you mean.

**Comment by Inqnuam** [comment]
```ts
// index.ts
import "./style1.css";
import "./style2.css";
import "./style3.css";
```

```css
/* style1.css */
@charset "utf-8";
@import url("https://fonts.googleapis.com/css?family=Oswald:300,400,700");
@import url(https://fonts.googleapis.com/css?family=Roboto:400,500);

@font-face {
  font-family: "VeraSeBd";
  src: url(https://mdn.github.io/css-examples/web-fonts/VeraSeBd.ttf);
}

.class1 {
  height: 909px;
}
```

```css
/* style2.css */
@charset "utf-8";

@font-face {
  font-family: "VeraSeBd";
  src: url("https://mdn.github.io/css-examples/web-fonts/VeraSeBd.ttf");
}

.class2 {
  width: 300px;
}
```
```css
/* style3.css */
.class3 {
  color: red;
}
@import url(https://fonts.googleapis.com/css?family=Roboto:400,500);
```

Current css bundle output
```css
@charset "UTF-8";
@import "https://fonts.googleapis.com/css?family=Oswald:300,400,700";
@import "https://fonts.googleapis.com/css?family=Roboto:400,500";

/* style1.css */
@font-face {
  font-family: "VeraSeBd";
  src: url(https://mdn.github.io/css-examples/web-fonts/VeraSeBd.ttf);
}
.class1 {
  height: 909px;
}

/* style2.css */
@font-face {
  font-family: "VeraSeBd";
  src: url(https://mdn.github.io/css-examples/web-fonts/VeraSeBd.ttf);
}
.class2 {
  width: 300px;
}

/* style3.css */
.class3 {
  color: red;
}
@import url(https://fonts.googleapis.com/css?family=Roboto:400,500);
```

Excepted/optimised output
```css
@charset "UTF-8";
@import "https://fonts.googleapis.com/css?family=Oswald:300,400,700";
@import "https://fonts.googleapis.com/css?family=Roboto:400,500";

/* style1.css */
@font-face {
  font-family: "VeraSeBd";
  src: url(https://mdn.github.io/css-examples/web-fonts/VeraSeBd.ttf);
}
.class1 {
  height: 909px;
}

/* style2.css */
.class2 {
  width: 300px;
}

/* style3.css */
.class3 {
  color: red;
}
```
