### ISSUE TITLE
Question: Can a plugin tell esbuild to omit the sourcemap for a generated code?

### ISSUE THREAD

**Issue by mhsdesign** [evanw/esbuild#2943]
Hi sorry to bother you - this is a pure aesthetical question about sourcemaps.

I build a css modules plugin that will tell esbuild to return this javascript file when i do `import style from "style.css"`

```js
import dependency_0 from "../reset.module.css"
import "css-modules://i6eqL892ECEOQ1Z2DuzOPfh97FRWhU6YpOX1VH95JW4.css"
export default {"bar":"_5OiSHG_bar " + dependency_0["reset"] + "","bar--top":"_5OiSHG_bar--top","bar--bottom":"_5OiSHG_bar--bottom",}
```

the thing is my chrome sources tab now also show these generated files (additionally to my "real" css map)
![image](https://user-images.githubusercontent.com/85400359/220557187-02a79fa6-ea5f-4848-9b2b-62fe76b3227d.png)

the real css map contents:
```css
.bar {
    composes: reset from '../reset.module.css';
    position: fixed;
    left: 0;
    z-index: var(--zIndex-CheckboxInput-Context);
    width: 100%;
    background-color: var(--colors-ContrastDarker);
    height: 41px;
    border-bottom: 1px solid var(--colors-ContrastDark);
}
.bar--top {
    top: 0;
}
.bar--bottom {
    bottom: 0;
}
```

i was just wondering how i can make the fake style.css (which is actutally a js file) disappear, and i though about telling esbuild to use an empty sourcemap at the end:

```js
import dependency_0 from "../reset.module.css"
import "css-modules://i6eqL892ECEOQ1Z2DuzOPfh97FRWhU6YpOX1VH95JW4.css"
export default {"bar":"_5OiSHG_bar " + dependency_0["reset"] + "","bar--top":"_5OiSHG_bar--top","bar--bottom":"_5OiSHG_bar--bottom",}
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFtdLAogICJtYXBwaW5ncyI6ICIiLAogICJuYW1lcyI6IFtdCn0K
```

but the sourcemap parser will just omit it (rightfully ^^) https://github.com/evanw/esbuild/blob/a5f781ecd5edeb3fb6ae8d1045507ab850462614/internal/js_parser/sourcemap_parser.go#L101

so i just want to let my plugin determine that esbuild should not generate sourcemaps for this generated file ^^

idk maybe i am the only one with this problem :joy: 

-----

btw really great work so far ;D I absolutely love it :heart: 
At neos https://github.com/neos/neos-ui we now bundle with esbuild which saves us 30 seconds of old webpack and babel time :D
450ms currently :exploding_head:
