### ISSUE TITLE
Feature: Convert Nested CSS when bundling 

### ISSUE THREAD

**Issue by mangelozzi** [evanw/esbuild#3030]
Just like the bundling can convert modern JS to older more compatible JS, the same would be great for CSS.

A new feature hitting browsers is nested CSS (https://caniuse.com/css-nesting).

Will ESBuild have an option to compile the CSS down to none nested versions until it becaomes mainstream enough to not have to perform the conversion when bundling?

I.e. this:
```
::slotted(:where(textarea, select, input:not(:where([type=checkbox], [type=radio])))) {
    color: blue;

    &:focus {
    color: red;
}
```

becomes:
```css
::slotted(:where(textarea, select, input:not(:where([type=checkbox], [type=radio])))) {
    color: blue;
}
::slotted(:where(textarea, select, input:not(:where([type=checkbox], [type=radio])))):focus {
    color: red;
}
```
Heres the W3C spec: https://www.w3.org/TR/css-nesting-1/
