### ISSUE TITLE
Nesting CSS with > only applies to the deepest rule

### ISSUE THREAD

**Issue by eduardtudor21** [evanw/esbuild#3046]
version: 0.17.5

Input
```css
.a {
  color: red;
  > .b {
    color: green;
     > .c {
       color: blue;
       > .d {
        color: blue;
      }
    }
  }
}
``` 

Output
```css
.a {
  color: red;
}
.a > .b {
  color: green;
}
.a .b > .c {
  color: blue;
}
.a .b .c > .d {
  color: blue;
}
``` 

I expected it to be `a. > .b > .c` like the example in [https://developer.chrome.com/articles/css-nesting/](https://developer.chrome.com/articles/css-nesting/). 
I'm not sure what's the impact because my simple css rules still works as expected.
