### ISSUE TITLE
CSS Nesting: multiple children

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#3096]
Think this is a bug in esbuild when transforming down CSS nesting...

This input needs no transforming, and all works. It will style `span` and `label` siblings of `input`:

```css
input + span,
input + label {
  color: red;
}
```

But introducing nesting:

```css
input {
  + span,
  + label {
    color: red;
  }
}
```

Results in this output:

```css
input :is(+ span, + label) {
  color: red;
}
```

Which is invalid and incorrect, and will not style the siblings `span` and `label` of `input`.

**Comment by joelmoss** [comment]
thanks for the fix, but the issue still persists with pseudo-elements...

```css
a {
  &::before,
  &::after {
    content: "???";
  }
}
```

which will result in...

```css
a:is(::before, ::after) {
  content: "???";
}
```

Which again, will not work.

**Comment by evanw** [comment]
As far as I can tell, pseudo-elements deliberately don't work with CSS nesting according to the CSS nesting specification (https://www.w3.org/TR/css-nesting-1/#ref-for-matches-pseudo%E2%91%A0):

> The [nesting selector](https://www.w3.org/TR/css-nesting-1/#nesting-selector) cannot represent pseudo-elements (identical to the behavior of the [:is()](https://www.w3.org/TR/selectors-4/#matches-pseudo) pseudo-class).

So I believe esbuild is working correctly here. Both `a { &::before {} }` and `a:is(::before) {}` are equivalent according to the specification, and are equally invalid. Transforming `a { &::before {} }` into `a::before {}` would be incorrect because it's not equivalent.

**Comment by joelmoss** [comment]
Well that's interesting, as this works in Chrome 113

```css
a {
  &::before,
  &::after {
    content: "???";
  }
}
```
