### ISSUE TITLE
Squashing unnecessary media queries during minification

### ISSUE THREAD

**Issue by JWo1F** [evanw/esbuild#3226]
## Problem:
When I use some framework to generate styles (tailwind, for example), I can get the following styles as output:
```css
@media (min-width: 1024px) {
  .md\:class {
    color: red;
  }
  @media (min-width: 1024px) {
    .md\:class {
      color: blue;
    }
  }
}
```

## Solution:
It can be seen that the final version should be as follows:
```css
@media (min-width: 1024px) {
  .md\:class {
    color: blue;
  }
}
```

When minifying css, it would be very nice to collapse such constructs. This will definitely reduce the output file and the problem is related to the minifier, not to the css framework, as it is quite valid css that can (and should) be compressed.

[[See esbuild try example here]](https://esbuild.github.io/try/#dAAwLjE4LjExAC0tbG9hZGVyPWNzcyAtLW1pbmlmeQBAbWVkaWEgKG1pbi13aWR0aDogMTAyNHB4KSB7CiAgLm1kXDpoMyB7CiAgICBmb250LXdlaWdodDogNTAwOwogICAgZm9udC1zaXplOiAxLjI1cmVtOwogICAgbGluZS1oZWlnaHQ6IDEuNjI1cmVtOwogIH0KICBAbWVkaWEgKG1pbi13aWR0aDogMTAyNHB4KSB7CiAgICAubWRcOmgzIHsKICAgICAgZm9udC1zaXplOiAycmVtOwogICAgICBsaW5lLWhlaWdodDogMi4zMTI1cmVtOwogICAgfQogIH0KfQ)

What do you think about it?
