### ISSUE TITLE
Possibly incorrect `css-syntax-error`?

### ISSUE THREAD

**Issue by brc-dd** [evanw/esbuild#3265]
[Prettier v3 formats some code like this:](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZBLAzgCgHQDcAOAtHAB7wBOUAhgDaE2pQDWhqkUANAAR5EAmEMFyoBtABbk4AMwBUAXgA6yAPQKFqkAF1uvQgKGiYVcgHM4MRSAD6AIxpVmSzQEokUCDBzvW7Z12AKUFxckDQQ5EhcknwA3IEAviAcIBD4MKjQ6MigxuQQAO4ACsYIWSi0+VQAnlnJNuRUYEzmAMpUALZwADKMcMhStOhwdQ1NrfiNjCbIMOQArsMgQ+2oM-OL6FM0cACKcx59SAM0Q8kAVugkLVu7+-D9g4sAjndwhXn4ZSBU6IRQcHA+ICkiBZlRUAwoCYAMIQdrtKjIb40GggzZQ7YAQRgs1QNjm8EKcHIPX+DxOizEMHaNAA6mJUPB0BMwHAWqVGahcIyqkiwOhaiBcAsAJJQIGwFpgcioNKY8UtGBVbbk04gfB5Ia0hr4JEauBDci4PrJRiGmDvKgmBGqxYTciGvkCkEaxgwWmoPgwMTIAAcAAZkpIXqhJJbrYijo9kkYbB6vT6kAAmZJzIYAFSoNjKxzVcHaNkBQL4XQcJjmVrgADFwgicVMkVQCRAQPF4kA)

```css
:is(.vp-external-link-icon, .vp-doc a[href*=":/\/"], .vp-doc a[target="_blank"]):not(.no-icon) {
  color: red;
}
```

to

```css
:is(
    .vp-external-link-icon,
    .vp-doc a[href*=":/\/"],
    .vp-doc a[target="_blank"]
  ):not(.no-icon) {
  color: red;
}
```

But with the latter syntax, esbuild gives this warning:

```
▲ [WARNING] Unexpected whitespace [css-syntax-error]

    <stdin>:1:4:
      1 │ :is(
        ╵     ^
```

If this is expected behavior, let me know. I'll create an issue at prettier.

## Reproduction

https://esbuild.github.io/try/#dAAwLjE4LjE1AC0tbG9hZGVyPWNzcwA6aXMoCiAgICAudnAtZXh0ZXJuYWwtbGluay1pY29uLAogICAgLnZwLWRvYyBhW2hyZWYqPSI6L1wvIl0sCiAgICAudnAtZG9jIGFbdGFyZ2V0PSJfYmxhbmsiXQogICk6bm90KC5uby1pY29uKSB7CiAgY29sb3I6IHJlZDsKfQ

## Related issues

https://github.com/vitejs/vite/issues/13914
