### ISSUE TITLE
Duplicated css declarations

### ISSUE THREAD

**Issue by Inqnuam** [evanw/esbuild#3292]
```css
/* styles.css */
body {
  backdrop-filter: blur(30px);
  -webkit-backdrop-filter: blur(30px);
}
```
```ts
// index.ts
import "./styles.css";
```

```js
// bundle.mjs
import esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["./index.ts"],
  platform: "browser",
  target: "safari12",
  bundle: true,
  outdir: "./out",
});

```

current css output

```css
/* styles.css */
body {
  -webkit-backdrop-filter: blur(30px);
  backdrop-filter: blur(30px);
  -webkit-backdrop-filter: blur(30px);
}
```

desired css output
```css
/* styles.css */
body {
  backdrop-filter: blur(30px);
  -webkit-backdrop-filter: blur(30px);
}
```

tested with 0.18.17 and 0.18.18

**Comment by evanw** [comment]
The duplicate rule that you don’t want is being automatically generated for you because of the `target` you set combined with esbuild’s automatic generation of prefixed declarations. The simplest solution is to just delete the `-webkit-backdrop-filter` and let esbuild generate it for you. Another solution is to enable rule deduplication with `minifySyntax: true`. Or you could rearrange the declarations so that `-webkit-backdrop-filter` comes before `backdrop-filter`.

**Comment by Inqnuam** [comment]
Thanks for your quick response!

Deleting "-webkit-backdrop-filter" is acceptable if its value is exactly the same as for backdrop-filter.
For some reason if need different values depending on browser such as:
```css
body {
  backdrop-filter: blur(30px);
  -webkit-backdrop-filter: blur(45px);
}
```
esbuild produce:
```css
body {
  -webkit-backdrop-filter: blur(30px);
  backdrop-filter: blur(30px);
  -webkit-backdrop-filter: blur(45px);
}
```

Also if we use an external library which already includes both "backdrop-filter" and "-webkit-backdrop-filter" it will be difficult to manipulate library's generated css to meet esbuild requirements.

Maybe we need a new build option for esbuild to change this behaviour ?
