### ISSUE TITLE
Deduplicate css class selectors

### ISSUE THREAD

**Issue by Inqnuam** [evanw/esbuild#3304]
```css
/* Original code */

body.myAwsomeClass.myAwsomeClass.myAwsomeClass.myAwsomeClass {
  color:red
}
```

```css
/* current output with --minify */

body.myAwsomeClass.myAwsomeClass.myAwsomeClass.myAwsomeClass{color:red}
```

```css
/* desired output */

body.myAwsomeClass{color:red}
```

If i'am the author of original code of course I'll don't duplicate class names as in the example.
In real world I have noticed that svelte compiler with css preprocessing emits this kind of css.
I'm not css expert but im not sure duplicating class names makes sense in this case. 

[reproduction](https://esbuild.github.io/try/#YgAwLjE5LjAALS1taW5pZnkgLS1idW5kbGUgLS1vdXRkaXI9ZGlzdABlAHN0eWxlcy5jc3MAYm9keS5teUF3c29tZUNsYXNzLm15QXdzb21lQ2xhc3MubXlBd3NvbWVDbGFzcy5teUF3c29tZUNsYXNzIHsKY29sb3I6cmVkCn0K) with esbuild online playground

**Comment by hyrious** [comment]
No, they have different specificity. For example the original code has `(0,4,1)` while the desired code has `(0,1,1)`, which means the former is more specific. This information is important for CSS engines to sort selectors. The following code will result in different styles:

```css
body.myAwsomeClass.myAwsomeClass.myAwsomeClass.myAwsomeClass{color:red} /* win */
body.foo{color:blue}
```

```css
body.myAwsomeClass{color:red}
body.foo{color:blue} /* win */
```

```html
<body class="myAwsomeClass foo">
```

https://polypane.app/css-specificity-calculator/#selector=body.myAwsomeClass.myAwsomeClass.myAwsomeClass.myAwsomeClass
