### ISSUE TITLE
local-css list-style-type invalid transform

### ISSUE THREAD

**Issue by vemoo** [evanw/esbuild#3325]
When transforming
```css
.event {
  list-style-type: none;
}
```
as `local-css`, `none` is treated as a local name, but it should be treated as a keyword: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

[repro](https://esbuild.github.io/try/#YgAwLjE5LjIAAGUAZW50cnkubW9kdWxlLmNzcwAuZXZlbnQgewogIGxpc3Qtc3R5bGUtdHlwZTogbm9uZTsKfQ)
