### ISSUE TITLE
Transform Media Queries Level 4 ?

### ISSUE THREAD

**Issue by kapouer** [evanw/esbuild#3465]
Hi,

it would be nice if esbuild could transform [Level 4 media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries#syntax_improvements_in_level_4) according to `target` settings.

Modern browser support is good, but doesn't go far back.

```css
@media only screen and (width <= 511px) {
  .stuff { width:300px; }
}
```

to

```css
@media only screen and (max-width: 511px) {
  .stuff { width:300px; }
}
```
