### ISSUE TITLE
Loader that doesn't modify original CSS references

### ISSUE THREAD

**Issue by matthewmueller** [evanw/esbuild#3535]
Hi there. 

There doesn't seem to be a loader to have ESBuild externalize or ignore asset references inside CSS.

Here's a demo: https://esbuild.github.io/try/#YgAwLjE5LjkALS1idW5kbGUgLS1sb2FkZXI6LndvZmYyPWVtcHR5IC0tbG9hZGVyOi53b2ZmPWVtcHR5IC0tbG9hZGVyOi50dGY9ZW1wdHkgLS1sb2FkZXI6LnBuZz1lbXB0eSAtLW91dGRpcj0uAGUAZW50cnkuanMAaW1wb3J0ICIuL2ZpbGUuY3NzIjsAAGZpbGUuY3NzAEBmb250LWZhY2UgewogIGZvbnQtZmFtaWx5OiAiTmFubyI7CiAgc3JjOiB1cmwoJ3B1YmxpYy9mb250cy9uYW5vLndvZmYyJykgZm9ybWF0KCd3b2ZmMicpLAogICAgICAgdXJsKCdwdWJsaWMvZm9udHMvbmFuby53b2ZmJykgZm9ybWF0KCd3b2ZmJyksCiAgICAgICB1cmwoJ3B1YmxpYy9mb250cy9uYW5vLnR0ZicpIGZvcm1hdCgndHJ1ZXR5cGUnKTsKfQoKZGl2IHsKCWJhY2tncm91bmQtaW1hZ2U6IHVybCgicHVibGljL2Fib3V0LnBuZyIpOwp9AABwdWJsaWMvZm9udHMvbmFuby53b2ZmAAAAcHVibGljL2ZvbnRzL25hbm8ud29mZjIAAABwdWJsaWMvZm9udHMvbmFuby50dGYAAABwdWJsaWMvYWJvdXQucG5nAA

In the demo above, I'm using empty, but I've tried most of the other loaders as well.

Input:

```css
@font-face {
  font-family: "Nano";
  src: url('public/fonts/nano.woff2') format('woff2'),
       url('public/fonts/nano.woff') format('woff'),
       url('public/fonts/nano.ttf') format('truetype');
}

div {
	background-image: url("public/about.png");
}
```

Where the expected output would maintain the same reference paths:

```css
@font-face {
  font-family: "Nano";
  src: url('public/fonts/nano.woff2') format('woff2'),
       url('public/fonts/nano.woff') format('woff'),
       url('public/fonts/nano.ttf') format('truetype');
}

div {
	background-image: url("public/about.png");
}
```

Then maybe with the assets discovered in the meta file. I expected the empty loader to do this, but it removes the paths instead (see demo).

Rationale: I'd like to use esbuild within the context of another build system that handles assets separately.

Thanks!
