### ISSUE TITLE
minimize var usage in CSS

### ISSUE THREAD

**Issue by jtarchie** [evanw/esbuild#3595]
- I noticed that some things could be added when minifying my CSS output from Tailwind.

For example,

```css
.dark\:text-gray-100{
  --tw-text-opacity:1;
  color:rgb(243 244 246/var(--tw-text-opacity))
}
```

Note: This is the output from `esbuild` above.

Since the var `--tw-text-opacity` is only used within this selector, we could rewrite as:

```css
.dark\:text-gray-100{
  color:rgb(243 244 246/1)
}
```

- How to verify unused and undefined variables.

For example,

```css
--tw-pan-x: ;
```

This variable gets declared with no value. Does CSS need it, then? It does not appear anywhere in my CSS file except in the declaration.

- Comparison of `var(--variable)` to actual length of `--variable` value. If the `--variable` value length is less than the `var` declaration, then replace it with the actual value.
