### ISSUE TITLE
css nesting lowering doesn't work when both a pseudo element selector and a class selector is used

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#3648]
For this input,
```css
.foo {
  &:after,
  & .bar {
    grid-area: 1 / 1 / 2 / 2;
  }
}
```
esbuild outputs
```css
.foo .bar,
.foo .bar {
  grid-area: 1 / 1 / 2 / 2;
}
```
. I expect
```css
.foo:after,
.foo .bar {
  grid-area: 1 / 1 / 2 / 2;
}
```
to be output.

Interestingly, the following works as expected:
```css
.foo {
  & .bar,
  &:after
   {
    grid-area: 1 / 1 / 2 / 2;
  }

  &:after {
    grid-area: 1 / 1 / 2 / 2;
  }

  &:before,
  &:after {
    grid-area: 1 / 1 / 2 / 2;
  }
}
```

[esbuild try](https://esbuild.github.io/try/#dAAwLjIwLjAALS1sb2FkZXI9Y3NzIC0tdGFyZ2V0PWNocm9tZTExMQAuZm9vIHsKICAmOmFmdGVyLAogICYgLmJhciB7CiAgICBncmlkLWFyZWE6IDEgLyAxIC8gMiAvIDI7CiAgfQoKICAmIC5iYXIsCiAgJjphZnRlcgogICB7CiAgICBncmlkLWFyZWE6IDEgLyAxIC8gMiAvIDI7CiAgfQoKICAmOmFmdGVyIHsKICAgIGdyaWQtYXJlYTogMSAvIDEgLyAyIC8gMjsKICB9CgogICY6YmVmb3JlLAogICY6YWZ0ZXIgewogICAgZ3JpZC1hcmVhOiAxIC8gMSAvIDIgLyAyOwogIH0KfQ)

Original issue: https://github.com/vitejs/vite/issues/15912
