### ISSUE TITLE
CSS media query range syntax not downleveled

### ISSUE THREAD

**Issue by Josh-Cena** [evanw/esbuild#3748]
[Playground](https://esbuild.github.io/try/#YgAwLjIwLjIALS10YXJnZXQ9Y2hyb21lNzAAZQBzdHlsZXMuY3NzAC5jb250YWluZXIgewogIHdpZHRoOiAxMDAlOwp9CgpAbWVkaWEgKHdpZHRoID4gNzY4cHgpIHsKICAuY29udGFpbmVyIHsKICAgIHdpZHRoOiA1MCU7CiAgfQp9CgphIHsKICAmOmhvdmVyIHsKICAgIGNvbG9yOiByZWQ7CiAgfQp9)

```css
.container {
  width: 100%;
}

@media (width > 768px) {
  .container {
    width: 50%;
  }
}

a {
  &:hover {
    color: red;
  }
}
```

```js
import * as esbuild from "esbuild";

const result = await esbuild.build({
  entryPoints: ["styles.css"],
  bundle: true,
  outdir: "dist",
  target: "chrome70",
});
console.log(result);
```

Compiled output:

```css
/* styles.css */
.container {
  width: 100%;
}
@media (width > 768px) {
  .container {
    width: 50%;
  }
}
a:hover {
  color: red;
}
```

Note that the nesting syntax is downleveled, but not the range syntax. Range syntax is only supported from Chrome 104. It should be possible to compile it to `min-width: 769px`, or otherwise throw an error.
