### ISSUE TITLE
Support CSS Anchor Positioning

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#3773]
- Spec: https://drafts.csswg.org/css-anchor-position-1/
- Ships in [Chrome 125](https://chromestatus.com/feature/5124922471874560)

**Comment by yisibl** [comment]
## Shorthand

```
position-try: <'position-try-order'>? <'position-try-options'>
```

### Input
```css
.foo {
  position-try-order: most-width;
  position-try-options: flip-block;
}
```

## Expected

```css
.foo {
  position-try: most-width flip-block;
}
```

## When `position-anchor` is present, `<anchor-element>` can be omitted from `anchor()` and `anchor-size()`

### Input

```css
.foo {
  position: absolute;
  position-anchor: --target-something;
  top: anchor(--target-something center, 20px);
  width: calc(anchor-size(--foo block) * 2);
}
```

### Expected

```css
.foo {
  position: absolute;
  position-anchor: --target-something;
  top: anchor(top, 20px);
  width: calc(anchor-size(block) * 2);
}
```

##  Converts keywords in `anchor()` to percentages.

https://drafts.csswg.org/css-anchor-position-1/#valdef-anchor-center

> Refers to a position a corresponding percentage between the [start](https://drafts.csswg.org/css-anchor-position-1/#valdef-anchor-start) and [end](https://drafts.csswg.org/css-anchor-position-1/#valdef-anchor-end) sides, with 0% being equivalent to start and 100% being equivalent to end.
> [center](https://drafts.csswg.org/css-anchor-position-1/#valdef-anchor-center) is equivalent to 50%.


## The [@position-try](https://drafts.csswg.org/css-anchor-position-1/#at-ruledef-position-try) Rule

1. Only specific attributes are allowed in `@position-try`, if others are present we need to throw a hint.
2. Remove the extra whitespace.

There are more details to discover, I've just listed the most common ones.
