### ISSUE TITLE
`layer()` functions without arguments in `@import` are incorrectly treated as valid

### ISSUE THREAD

**Issue by romainmenke** [evanw/esbuild#3993]
Currently esbuild is failing this test: https://github.com/romainmenke/css-import-tests/tree/main/tests/002-sub-features/003-at-layer/018

```css
@import url("green.css") layer; /* valid */
@import url("red.css") layer(); /* must be invalid */
```

It seems that esbuild treats `layer()` as valid and transpiles it to:

```css
/* tests/002-sub-features/003-at-layer/018/red.css */
@layer {
  .box {
    background-color: red;
  }
}
```
