### ISSUE TITLE
CSS nesting `&&` is lowered incorrectly

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#3997]
[According to the spec](https://www.w3.org/TR/css-nesting-1/#:~:text=/*%20Again%2C%20silly%2C%20but%20can%20even%20be%20doubled%20up.%20*/%0A.foo%20%7B%0A%20%20color%3A%20blue%3B%0A%20%20%26%26%20%7B%20padding%3A%202ch%3B%20%7D%0A%7D%0A/*%20equivalent%20to%0A%20%20.foo%20%7B%20color%3A%20blue%3B%20%7D%0A%20%20.foo.foo%20%7B%20padding%3A%202ch%3B%20%7D%0A*/), for the following input,
```css
.foo {
  color: blue;
  && { padding: 2ch; }
}
```
the lower result should be
```css
.foo { color: blue; }
.foo.foo { padding: 2ch; }
```

But esbuild outputs,
```css
.foo {
  color: blue;
}
.foo {
  padding: 2ch;
}
```
which has a different specificity ([esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAALS1sb2FkZXI9Y3NzIC0tc3VwcG9ydGVkOm5lc3Rpbmc9ZmFsc2UALmZvbyB7CiAgY29sb3I6IGJsdWU7CiAgJiYgeyBwYWRkaW5nOiAyY2g7IH0KfQ)).

Original issue: https://github.com/vitejs/vite/issues/18843
