### ISSUE TITLE
Potentially update CSS nesting for additional spec changes

### ISSUE THREAD

**Issue by evanw** [evanw/esbuild#4063]
I just became aware that Chrome recently changed how CSS nesting works again: https://web.dev/blog/css-nesting-cssnesteddeclarations. Specifically rules consisting of mixed nested and non-nested CSS now resolve in a different order than before. This should be investigated to understand exactly what changed and what should be done about it.

**Comment by yisibl** [comment]
We need to ensure that the CSS compiled by esbuild will pass all WPT tests with a green color.
https://github.com/web-platform-tests/wpt/blob/master/css/css-nesting/nesting-basic.html

## input
```css
.test-10 {
  & {
    background-color: red;
  }
  background-color: green;
}
```

## esbuild [output](https://esbuild.github.io/try/#dAAwLjI3LjMALS1sb2FkZXI9Y3NzIC0tdGFyZ2V0PWNocm9tZTk5AC50ZXN0LTEwIHsKICAmIHsKICAgIGJhY2tncm91bmQtY29sb3I6IHJlZDsKICB9CiAgYmFja2dyb3VuZC1jb2xvcjogZ3JlZW47Cn0)

```css
.test-10 {
  background-color: green;
}
.test-10 {
  background-color: red;
}
```

## expected

```css
.test-10 {
  background-color: red;
}
.test-10 {
  background-color: green;
}
```
