### ISSUE TITLE
Nesting Disabled Causes Contextual Changes in Output

### ISSUE THREAD

**Issue by alan-agius4** [evanw/esbuild#4152]
When CSS nesting is disabled, the output changes the context of the nested rules. Specifically, the nested selectors no longer target the original parent class and instead use a more generic context. This results in unexpected behavior in the final CSS.

**Input:**
```css
::ng-deep .first-class {
  color: red;
  .second-class {
    font-weight: bold;
  }
}
```

**Output:**
```css
/* entry.css */
::ng-deep .first-class {
  color: red;
}
:is() .second-class {
  font-weight: bold;
}
```

**Expected Output:**
```css
/* entry.css */
::ng-deep .first-class {
  color: red;
}
::ng-deep .first-class .second-class {
  font-weight: bold;
}
```

Repro: https://esbuild.github.io/try/#YgAwLjI1LjIAewogICdidW5kbGUnOiB0cnVlLAonc3VwcG9ydGVkJzogeyduZXN0aW5nJzogZmFsc2V9Cn0AZQBlbnRyeS5jc3MAOjpuZy1kZWVwIC5maXJzdC1jbGFzcyB7CiAgY29sb3I6IHJlZDsKICAuc2Vjb25kLWNsYXNzIHsKICAgIGZvbnQtd2VpZ2h0OiBib2xkOwogIH0KfQAAZmlsZS5qcwA
