### ISSUE TITLE
CSS value `stretch` is not being vendor prefixed

### ISSUE THREAD

**Issue by waterplea** [evanw/esbuild#4184]
When I write:
```css
.class {
  width: stretch;
}
```
it is supposed to be prefixed as:
```css
.class {
    width: -webkit-fill-available;
    width: -moz-available;
    width: stretch;
}
```
but it is left untouched. Got redirected here from this issue: https://github.com/angular/angular-cli/issues/30302
