### ISSUE TITLE
The order of CSS imports is not respected

### ISSUE THREAD

**Issue by iamakulov** [evanw/esbuild#465]
Not sure whether this is related to #399 or a separate issue.

### Test case

Consider the following project:

```js
// index.js
import "./transitive-import.js"
import "./b.css"
import "./a.css"

console.log("foo")

// transitive-import.js
import "./c.css"
```

```css
/* a.css */
body {
  color: blue;
}

/* b.css */
body {
  color: red;
}

/* c.css */
body {
  color: green;
}
```

### Actual behavior

If you bundle the project with ESBuild:

```
npx esbuild ./index.js --bundle --outdir=./build
```

the resulting `build/index.css` file will look as follows:

```css
/*** build/index.css ***/
/* a.css */
body {
  color: blue;
}

/* b.css */
body {
  color: red;
}

/* c.css */
body {
  color: green;
}
```

The problem here is that ESBuild changes the order of CSS modules. This changes the specificity of rules – and, ultimately, changes how the page would look. (The text would be green instead of blue.)

### Expected behavior

The expected behavior is for ESBuild to bundle CSS imports in the order of their appearance in the module tree (with depth-first traversal). That’s how webpack does that (AFAIK).

You can test the webpack behavior with the following config:

<details>

`package.json`:

```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "css-loader": "5.0.0",
    "mini-css-extract-plugin": "1.0.0",
    "webpack": "5.1.3",
    "webpack-cli": "^4.0.0"
  }
}
```

`webpack.config.js`:

```js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  entry: "./index.js",
  output: {
    path: __dirname + "/build",
    filename: "[name].js"
  },
  plugins: [new MiniCssExtractPlugin()],
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, "css-loader"]
      }
    ]
  }
};
```

Building the project with the above config (`npx webpack`) produces `build/main.css` that looks as follows:

```css
body {
  color: green;
}

body {
  color: red;
}

body {
  color: blue;
}
```

</details>

**Comment by evanw** [comment]
Thanks for reporting this. This will be good to fix. I think it's somewhat related to #399 but it's different enough that I'd like to keep this as a separate issue.

**Comment by nitzanorchestra** [comment]
I have the same problem. 
Example: 
I work with react, when I inject a class from parent to child the parent class should be stronger but it always ends up the contrary: the child class overrides the parent. 
(btw, I use snowpack and esbuild)

**Comment by evanw** [comment]
> The expected behavior is for ESBuild to bundle CSS imports in the order of their appearance in the module tree (with depth-first traversal).

I initially interpreted this to mean "evaluate the CSS file _once_ at the place of the _first_ import in depth-first order" where each file is visited at most once. That's how JavaScript imports work and that's the way esbuild's CSS bundler currently works. But I just realized that this is incorrect. The semantics of CSS @import is more like @include than @import. From the specification:

> user agents must treat the contents of the stylesheet as if they were written in place of the @import rule

I'm not sure why it's specified this way since it seems like surprising and unexpected behavior to me. But that's the way CSS actually works. So "bundling CSS imports in the order of their appearance in the module tree" would have to mean "evaluate the CSS file _all over again_ at the place of _every_ import in depth-first order" where the depth-first order can re-visit the same file an unbounded number of times. This can result in a combinatorial explosion of code for deep @import graphs. Here's an example of the difference:

* **entry.css**

    ```css
    @import "./file1.css";
    @import "./file2.css";
    ```

* **reset.css**

    ```css
    body {
      font-size: 10px;
      line-height: 10px;
    }
    ```

* **file1.css**

    ```css
    @import "./reset.css";
    body {
      font-size: 20px;
    }
    ```

* **file2.css**

    ```css
    @import "./reset.css";
    body {
      line-height: 20px;
    }
    ```

Running this CSS in the browser will result in a font size of 10px but bundling this CSS with esbuild and then running it in the browser will currently result in a font size of 20px. This is because esbuild currently only evaluates each file once at the location of the first @import in depth-first order instead of re-evaluating each file at every @import in depth-first order.

I wonder if it would be equivalent to just evaluate the CSS file _once_ at the place of the _last_ import in depth-first order. Instead of having the bundler recursively expand all @import statements, which would be crazy and cause massive code bloat. Placing the CSS last instead of first could potentially break some use cases such as e.g. importing a reset stylesheet from multiple files and then trying to override it below the import (the example above). A file further on in the bundle could re-import the reset stylesheet and erase the overrides due to CSS specificity rules. But that's how CSS works so ¯\\_(ツ)_/¯. A CSS bundler shouldn't not deviate from CSS semantics just because the semantics are unintuitive.

I wonder what other bundlers do here. I'm also having trouble figuring out what ordering even means for dynamic JavaScript imports that then import CSS code (see https://github.com/evanw/esbuild/issues/608#issuecomment-777388780), but that's another topic.
