### ISSUE TITLE
Skip over a leading BOM in CSS files

### ISSUE THREAD

**Issue by David-Buyer** [evanw/esbuild#776]
Hello, it seems the @import statement in .css file when trying to bundling it, does not work. I get the following error ( the resulting bundle does not include correctly the code where @import points:

```
css/app.css: warning: Unexpected "@import"
    1 │ ﻿@import "./bootstrap/bootstrap.min.css";
      ╵    ~~~~~~~

1 warning
```

-> _app.css_ 

```css
@import "./bootstrap/bootstrap.min.css";
html, body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
/* ..... */
}
```

->  _esbuild-config.js_

```js
require('esbuild').build({
            entryPoints: ['./css/app.css'],
            bundle: true,
            outfile: './wwwroot/css/app.min.css',
            minify: true,
        })
```

But if i place @import statement at bottom or the in middle of the app.css file, then it works. The issue seems to happen just if the @import statement is placed on top.

Maybe there's something i wrong but i don't know what. Please check it about.

esbuild version is: 0.8.43
