### ISSUE TITLE
Manually resolved path in CSS url()

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#831]
So I have a plugin that resolves all CSS `url()` directives to a custom URL path. For example:

```css
body {
  background: url('./user/avatar.png');
}
```

Which should return:

```css
body {
  background: url('/images/user/avatar.png');
}
```

Now I know the `files` loader will rewrite the image file name, but I do not want that, and need to maintain the path structure, while also resolving relative and absolute paths.

The problem I have is that the resulting CSS ends up being:

```css
body {
  background: url(data:text/plain;base64,L2xpYi9hdmF0YXIucG5n);
}
```

Which is incorrect.

Here's my plugin:

```javascript
    build.onResolve({ filter: /\.png$/ }, args => {
      return {
        path: resolve(args.resolveDir, args.path),
        namespace: 'image'
      }
    })

    build.onLoad({ filter: /\.png$/, namespace: 'image' }, args => {
      console.log(args)

      return {
        contents: args.path.slice(absWorkingDir.length),
        loader: 'text'
      }
    })
```

So even though I'm returning the `text` loader, it's converting it to a data URL. Is that expected behaviour?

thanks in advance
