### ISSUE TITLE
css empty rule should be eliminate

### ISSUE THREAD

**Issue by susiwen8** [evanw/esbuild#850]
In css file there are some empty rulesets, `esbuild` fail to remove them in bundle and minify.
```css
.a {
    
}
.b { color: red;}

@keyframes test {
    from {}
    to {
        color: red;
    }
}
```

it should be
```css
/* in webpack */
.b{color:red}@keyframes test{to{color:red}}
```
but `esbuild` save them
```css
/* in esbuild */
.a{}.b{color:red}@keyframes test{0%{}to{color:red}}
```
