### ISSUE TITLE
Hashes or queries in imports

### ISSUE THREAD

**Issue by normanrz** [evanw/esbuild#862]
I am using the font awesome icons for my project. The module provided css file uses hashes (e.g. `url("../webfonts/fa-solid-900.svg#fontawesome")`) and querystrings (e.g. `url("../webfonts/fa-solid-900.eot?#iefix")`) in the font imports. Esbuild doens't resolve those.

I think the expected behavior would be to ignore both hash and querystring parts of a URL when resolving, but keeping them in the output css. This is also how webpack handles it.

I made a small repo to reproduce the issue: https://github.com/normanrz/esbuild-sass-bug/tree/esbuild 
Note the `esbuild` branch. Run with `yarn install && node build.js`

**Comment by evanw** [comment]
> Run with `yarn install && node build.js`

Did you perhaps forget to add `build.js` to git?

**Comment by normanrz** [comment]
Yes, I added it now. Sorry about that!

**Comment by evanw** [comment]
When I run that I get lots of errors that look like this:

```
 > node_modules/@fortawesome/fontawesome-free/css/all.css: error: File could not be loaded: node_modules/@fortawesome/fontawesome-free/webfonts/fa-brands-400.ttf
    4592 │ ...at("woff"), url("../webfonts/fa-brands-400.ttf") format("truety...
         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But this is just because no loader has been configured for that file type. If you add something like this:

```diff
 const esbuild = require('esbuild');
 
 esbuild.build({
   entryPoints: ['index.js'],
   bundle: true,
   outfile: 'bundle.js',
+  loader: {
+    '.eot': 'file',
+    '.woff': 'file',
+    '.woff2': 'file',
+    '.svg': 'file',
+    '.ttf': 'file',
+  },
 }).catch((e) => console.error(e.message));
```

then the files load fine and preserve the query/hash in the imports:

```css
/* ... in bundle.css */
@font-face {
  font-family: "Font Awesome 5 Brands";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: 
    url(fa-brands-400.F47772JC.eot);
  src: 
    url(fa-brands-400.F47772JC.eot?#iefix) format("embedded-opentype"), 
    url(fa-brands-400.TY2VVPNB.woff2) format("woff2"), 
    url(fa-brands-400.GCVJUSS7.woff) format("woff"), 
    url(fa-brands-400.DV4GNJY3.ttf) format("truetype"), 
    url(fa-brands-400.HDM7XGLW.svg#fontawesome) format("svg");
}
```

This is expected because the feature to preserve the query/hash was recently added to fix #826. Is there more information required to reproduce your issue?
