### ISSUE TITLE
CSS conditional imports

### ISSUE THREAD

**Issue by martinring** [evanw/esbuild#953]
The current implementation does not support [conditional imports](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) at all and complains about invalid syntax if media or supports queries come after an import. It would be great if that was handled. I see two options:

1. give out a warning, that conditional imports are not supported
2. wrap the imported css into a query block such that `b.css` in the following example

   ````css
   /* file a.css */
   * { color: fuchsia }   
   ````
   
   and

   ````css
   /* file b.css */
   * { font-weight: bold }
   @import ('./a.css') print;
   ````
   
   would become

   ````css
   * { font-weight: bold }
   @media print {
      * { color: fuchsia }
   }
   ````
